### ISSUE TITLE
Challenge Mode

### ISSUE THREAD

**Issue by mikafinja** [Draradech/NewtonWars#11]
Implement a one on one challenge mode. Players get infint power and have two or five minute to shoot eachother as often as possible. The player with the most kills wins. 

If there is a draw, the next hit makes the winner.

**Comment by Draradech** [comment]
Is this different enough from starting with "./nw rate 200.0" (+ maybe "extrapoints off") to implement as its own gamemode (only missing the draw clause, I think). Looking for input.

Edit: On second look, this is older than the implementation of game rounds. Can be closed?
